### ISSUE TITLE
图书城输入等级和结果中等级不一样

### ISSUE THREAD

**Issue by lzb16** [WANGPeisheng1997/JiaGuoMengCalculator#11]
如图所示，图书城等级输入1200，结果中为1202；输入1217，结果为1218

![1](https://user-images.githubusercontent.com/3593723/66141022-a35dcf00-e635-11e9-9679-28bfb8b7073c.png)
![2](https://user-images.githubusercontent.com/3593723/66141034-a6f15600-e635-11e9-9f51-7cc2ac7a8571.png)

**Comment by ShawnIL** [comment]
这是升级完了的结果啊。。

**Comment by lzb16** [comment]
啊，填了金币数就输出的升级完的结果吗？
那还有个问题，如果是升级完的结果，那结果中的优先升级是不是应该是升级了的建筑？
但我的结果中优先升级推荐的是学校，结果如下：

最优策略：
工业建筑：造纸厂、电厂、纺织厂
商业建筑：学校、图书城、民食斋
住宅建筑：人才公寓、中式小楼、空中别墅

总秒伤： 638.82bb

各建筑等级：
造纸厂     	 1100
电厂      	 1050
纺织厂     	 1126
学校      	 1110
图书城     	 1218
民食斋     	 1101
人才公寓    	 1000
中式小楼    	 1050
空中别墅    	 1000

各建筑秒伤：
造纸厂     	 23.52bb
电厂      	 3.68bb
纺织厂     	 5.91bb
学校      	 64.23bb
图书城     	 538.98bb
民食斋     	 1.35bb
人才公寓    	 22.89aa
中式小楼    	 388.84aa
空中别墅    	 24.85aa

优先升级: 学校
每金币收益: 3.2876317439999994e-05

**Comment by ShawnIL** [comment]
这个是指这点钱花完之后，下一个要升级的就是学校了。

**Comment by lzb16** [comment]
好的，明白了，谢谢~
