### ISSUE TITLE
IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by zbdehh** [WANGPeisheng1997/JiaGuoMengCalculator#14]
![TIM截图20191004112838](https://user-images.githubusercontent.com/24779371/66179098-45af9e00-e69a-11e9-978f-51664e18d3ec.png)
错误提示如上 是什么等级有限制嘛？

**Comment by ShawnIL** [comment]
你填了多少啊。。

**Comment by zbdehh** [comment]
![image](https://user-images.githubusercontent.com/24779371/66180816-00429f00-e6a1-11e9-9b8e-01e06969b4f7.png)

**Comment by zhugezuo** [comment]
你纺织厂数字太大了呀

**Comment by ShawnIL** [comment]
纺织厂11000是个什么鬼。。。
