### ISSUE TITLE
黑名单保存失败

### ISSUE THREAD

**Issue by zhugezuo** [WANGPeisheng1997/JiaGuoMengCalculator#15]
经过一次”保存并计算最优排布“之后，再修改配置然后点”保存配置文件“按钮，config.json文件中的"blacklist"和”gold“部分会被还原。再次点击右侧的”保存并计算最优排布“在也不会生效。
![image](https://user-images.githubusercontent.com/19367341/66220438-99a09e00-e6ff-11e9-954f-37d6b219821f.png)

**Comment by ShawnIL** [comment]
之前代码有一处没有使用deepcopy，使黑名单会把建筑永久移除。现在已经修复了。
