### ISSUE TITLE
配置界面缺少离线收入的加成选项

### ISSUE THREAD

**Issue by curiositer** [WANGPeisheng1997/JiaGuoMengCalculator#17]
各类加成里面没有离线收入的加成填写位置，如果可以的话把这个加进去吧，辛苦啦！

**Comment by ShawnIL** [comment]
这个应该是最终版了，不会加入新功能了。。国庆结束大家都得上班，没什么人玩了。。我也没什么动力更新了。。

**Comment by curiositer** [comment]
哈哈哈，好的，这项目让我长见识了，真的是活学活用啊，佩服佩服！！
