### ISSUE TITLE
升级计算错误

### ISSUE THREAD

**Issue by flython** [WANGPeisheng1997/JiaGuoMengCalculator#18]
![image](https://user-images.githubusercontent.com/14855943/66302020-c7b5f600-e92a-11e9-855b-ae05845fed43.png)
如图，5cc就能升级1224的图书馆不太可能8，测试4cc不能升级，5cc就显示可以

**Comment by ShawnIL** [comment]
计算后的建筑会额外多升1级，保证你花完钱之后知道下一个该升谁。
