### ISSUE TITLE
关于性能提升的讨论

### ISSUE THREAD

**Issue by zz920** [WANGPeisheng1997/JiaGuoMengCalculator#19]
原有程序有不少可以优化的地方，
1. 使用panda原生的结构有可能导致消耗了大量IO时间。
2. 在运行时仅有单核在运行。

针对以上两点做了一下优化，以下是测试结果：

测试环境：
ubuntu18.04.1LTS
4核8线程 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz

测试 master branch code:
100%,05:45<00:00|███████████████████████████████████████████████████████████████████|1728000/1728000.0,4996.35it/s
31%,04:04<09:22|█████████████████████                                               |535327/1728000.0,2120.42it/s (实在太久了，就中止了)

测试 dev-enhancement branch - first commit:
100%,00:54<00:00|███████████████████████████████|1728000/1728000.0,31690.21it/s
100%,02:48<00:00|██████████████████████████████████████████████████████████████████|1728000/1728000.0,10237.53it/s

测试 dev-enhancement branch - second commit:

将原有172w个求解分成16组，由8个worker执行（应该可以进一步优化）
100%,00:10<00:00|███████████████████████████████████████████████████████████|16/16, 1.56it/s 
100%,00:41<00:00|███████████████████████████████████████████████████████████|16/16, 2.59s/it

**Comment by zz920** [comment]
pr: #20

**Comment by ShawnIL** [comment]
感谢！
