### ISSUE TITLE
点击计算后程序shutdown，并提示报错

### ISSUE THREAD

**Issue by Tang-DJ** [WANGPeisheng1997/JiaGuoMengCalculator#2]
config.json:
`{
    "buildings": {
        "\u6728\u5c4b": {
            "star": 4,
            "level": 652,
            "buff": 0
        },
        "\u5c45\u6c11\u697c": {
            "star": 4,
            "level": 675,
            "buff": 0
        },
        "\u94a2\u7ed3\u6784\u623f": {
            "star": 4,
            "level": 675,
            "buff": 0
        },
        "\u5e73\u623f": {
            "star": 4,
            "level": 500,
            "buff": 0
        },
        "\u5c0f\u578b\u516c\u5bd3": {
            "star": 3,
            "level": 500,
            "buff": 150
        },
        "\u4eba\u624d\u516c\u5bd3": {
            "star": 3,
            "level": 675,
            "buff": 0
        },
        "\u82b1\u56ed\u6d0b\u623f": {
            "star": 2,
            "level": 501,
            "buff": 0
        },
        "\u4e2d\u5f0f\u5c0f\u697c": {
            "star": 2,
            "level": 500,
            "buff": 150
        },
        "\u7a7a\u4e2d\u522b\u5885": {
            "star": 1,
            "level": 500,
            "buff": 100
        },
        "\u590d\u5174\u516c\u9986": {
            "star": 0,
            "level": 800,
            "buff": 0
        },
        "\u4fbf\u5229\u5e97": {
            "star": 4,
            "level": 675,
            "buff": 0
        },
        "\u4e94\u91d1\u5e97": {
            "star": 4,
            "level": 650,
            "buff": 0
        },
        "\u670d\u88c5\u5e97": {
            "star": 4,
            "level": 626,
            "buff": 0
        },
        "\u83dc\u5e02\u573a": {
            "star": 4,
            "level": 675,
            "buff": 0
        },
        "\u5b66\u6821": {
            "star": 4,
            "level": 550,
            "buff": 0
        },
        "\u56fe\u4e66\u57ce": {
            "star": 2,
            "level": 550,
            "buff": 0
        },
        "\u5546\u8d38\u4e2d\u5fc3": {
            "star": 2,
            "level": 500,
            "buff": 0
        },
        "\u52a0\u6cb9\u7ad9": {
            "star": 2,
            "level": 500,
            "buff": 0
        },
        "\u6c11\u98df\u658b": {
            "star": 2,
            "level": 600,
            "buff": 0
        },
        "\u5a92\u4f53\u4e4b\u58f0": {
            "star": 1,
            "level": 500,
            "buff": 0
        },
        "\u6728\u6750\u5382": {
            "star": 4,
            "level": 650,
            "buff": 0
        },
        "\u98df\u54c1\u5382": {
            "star": 4,
            "level": 675,
            "buff": 0
        },
        "\u9020\u7eb8\u5382": {
            "star": 4,
            "level": 551,
            "buff": 0
        },
        "\u6c34\u5382": {
            "star": 3,
            "level": 500,
            "buff": 0
        },
        "\u7535\u5382": {
            "star": 4,
            "level": 673,
            "buff": 0
        },
        "\u94a2\u94c1\u5382": {
            "star": 4,
            "level": 675,
            "buff": 0
        },
        "\u7eba\u7ec7\u5382": {
            "star": 2,
            "level": 500,
            "buff": 0
        },
        "\u96f6\u4ef6\u5382": {
            "star": 2,
            "level": 550,
            "buff": 0
        },
        "\u4f01\u9e45\u673a\u68b0": {
            "star": 2,
            "level": 550,
            "buff": 0
        },
        "\u4eba\u6c11\u77f3\u6cb9": {
            "star": 1,
            "level": 500,
            "buff": 0
        }
    },
    "buffs": {
        "policy": {
            "global": 500,
            "online": 200,
            "residence": 300,
            "commerce": 300,
            "industry": 500,
            "jiaguozhiguang": 75
        },
        "album": {
            "global": 70,
            "online": 70,
            "residence": 120,
            "commerce": 150,
            "industry": 150
        },
        "mission": {
            "global": 0,
            "online": 0,
            "residence": 0,
            "commerce": 0,
            "industry": 0
        }
    }
}`

wrong message:
`Traceback (most recent call last):
  File "/Users/user/program/other/JiaGuoMengCalculator/ui.py", line 230, in calculate
    calculator = Calculator(config)
  File "/Users/user/program/other/JiaGuoMengCalculator/algorithm.py", line 39, in __init__
    self.buildStars[star].append(build)
KeyError: 0
[1]    25022 abort      /usr/local/bin/python3.7 main.py`

hope：
当输入数字不合法时，希望能够进行数字验证，添加dialog提示，而不是程序运行失败直接关闭。

**Comment by ShawnIL** [comment]
明天会更新的，今天实在搞不动了

**Comment by Dr-Shirakawa** [comment]
星级填0会直接shutdown

**Comment by ShawnIL** [comment]
更新了，增加黑名单功能，不要在星级里填0 = =
