### ISSUE TITLE
升级所需数据有差异

### ISSUE THREAD

**Issue by jimlion-jx** [WANGPeisheng1997/JiaGuoMengCalculator#23]
在紫色稀有为1319等级时，设置还有100dd金币，计算升级方案为1319+1然后还有别的加成，然而1318的稀有升级一次就需要102dd，100dd升级紫色稀有做不到。upgrade的csv里面D列升级所需消耗是对的，应该是计算问题，代码看不太懂。
我的CPU是AMD ryzen5-2500u
![家国梦升级](https://user-images.githubusercontent.com/56325211/66439684-077ff900-ea63-11e9-84b2-c0775e5ad61e.png)

**Comment by ShawnIL** [comment]
见issue18
