### ISSUE TITLE
已按说明拉黑7个建筑，保存后点计算仍然闪退

### ISSUE THREAD

**Issue by ghost** [WANGPeisheng1997/JiaGuoMengCalculator#6]
无论如何点保存计算就闪退…

**Comment by ShawnIL** [comment]
可以提供一下截图吗

**Comment by ghost** [comment]
刚实验一共就保留9个建筑还是闪退…emmm是需要什么截图呢？什么报错都没有的。

**Comment by ShawnIL** [comment]
截一下你填的数据

**Comment by ghost** [comment]
应该是找到问题了。没有的图鉴我填的都是0，然后就会闪退（即使拉黑了）。如果都填1再拉黑就可以出结果了。

**Comment by ShawnIL** [comment]
这个我在nga帖子里写了。。我github上也加个提示吧。。

**Comment by husiwei158** [comment]
我也有一样的问题，附上截图
<img width="676" alt="2ffede90fef0eca3e920e4988f1e774" src="https://user-images.githubusercontent.com/43077523/66107253-5ad0f200-e5f2-11e9-81f7-e99653d68b8a.png">
<img width="663" alt="067e4a5d51bcba9ab2ca3c7aac35f78" src="https://user-images.githubusercontent.com/43077523/66107260-5e647900-e5f2-11e9-8306-240c63c3f246.png">
跑完之后就退出了

**Comment by ghost** [comment]
后来没再看nga的帖子直接从在线网页过来的…在GitHub里加一下说明吧，谢谢~
