### ISSUE TITLE
更改了所有0之后，还是在跑完之后不出结果

### ISSUE THREAD

**Issue by husiwei158** [WANGPeisheng1997/JiaGuoMengCalculator#7]
下面附上结果：
<img width="664" alt="1c64cedb74e0b45a56a8bc59686c2c7" src="https://user-images.githubusercontent.com/43077523/66107579-31649600-e5f3-11e9-9122-5e4540d9a670.png">
不知道是什么问题

**Comment by husiwei158** [comment]
如果有其他的信息需求，请随时联系我

**Comment by ShawnIL** [comment]
在文件头部加上#coding=utf-8

**Comment by husiwei158** [comment]
<img width="486" alt="715b828463a52ac24cbd0c0e59be478" src="https://user-images.githubusercontent.com/43077523/66111066-b1dac500-e5fa-11e9-9a2b-7dad8f1718f7.png">
在main.py头部吗?

**Comment by ShawnIL** [comment]
在每一个py头部都加一下吧

**Comment by husiwei158** [comment]
在所有py文件头部加了#coding = utf-8, 但还是存在同样的问题

**Comment by ShawnIL** [comment]
问题应该出在识别不出中文，因为有很多打印出来的信息都是中文的= =

**Comment by canpus** [comment]
大佬大佬，可不可以做以下几个功能：


1.计算接下来一段时间内（比如6小时或者12小时，或者自己指定一个时间）的收益，然后根据当前建筑的升级收益率和加成倍率，给出升级建议。


2.直接把城市任务和政策放到下拉菜单里面去，也就是集成在程序里面。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"王沛晟"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月3日(星期四) 下午4:34
收件人:&nbsp;"WANGPeisheng1997/JiaGuoMengCalculator"<JiaGuoMengCalculator@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [WANGPeisheng1997/JiaGuoMengCalculator] 更改了所有0之后，还是在跑完之后不出结果 (#7)




问题应该出在识别不出中文，因为有很多打印出来的信息都是中文的= =

**Comment by husiwei158** [comment]
> 问题应该出在识别不出中文，因为有很多打印出来的信息都是中文的= =

我自己想想办法吧

**Comment by husiwei158** [comment]
我查了一下，这一类的错误基本都通过在print x 后面加 .encode(‘utf-8’) 来解决，你输出结果的部分可以加这个吗？如果可以的话，请告诉一下在哪个py文件里，谢谢

**Comment by ShawnIL** [comment]
可以的，在algorithm.py里面
