### ISSUE TITLE
点击“保存并计算”，1秒后闪退

### ISSUE THREAD

**Issue by cesaryuan** [WANGPeisheng1997/JiaGuoMengCalculator#8]
### **如图所示：**
![BUG](https://user-images.githubusercontent.com/35998162/66115876-fe5dda80-e5d1-11e9-9b8d-99de7d85e84e.gif)

**Comment by ShawnIL** [comment]
再看一遍使用说明。。。

**Comment by cesaryuan** [comment]
我的锅。。。
