### ISSUE TITLE
最优结果结算有误

### ISSUE THREAD

**Issue by As3ass1n** [WANGPeisheng1997/JiaGuoMengCalculator#9]
![image](https://user-images.githubusercontent.com/18623783/66118891-13566000-e60a-11e9-8b56-d4bb435d5a7b.png)

我的搭配目前为 

 工业  | 商业 | 住宅 
 ---------- | ---------- | ---------- 
  造纸厂(5星 1001) | 民食寨(3星 1001)  | 人才公寓(4星 1001) 
   电厂(5星 1001) |  图书城(4星 1155)  | 空中别墅 (2星 1001) 
  纺织厂(5星 1001) |  学校(5星 1001) | 中式小楼(3星 1001) 

实际搭配收入为在线75.1bb/s 离线26.1bb/s

版本： 1.2 
运行的exe文件

**Comment by ShawnIL** [comment]
更新到2.0

**Comment by As3ass1n** [comment]
> 更新到2.0

好的 我试试

**Comment by As3ass1n** [comment]
> 更新到2.0

更新2.0之后，建筑搭配一致，计算结果为75.78bb 实际是75.1bb

**Comment by ShawnIL** [comment]
有截图吗

**Comment by As3ass1n** [comment]
![image](https://user-images.githubusercontent.com/18623783/66122489-6502e880-e612-11e9-9336-623791314d34.png)

政策目前在第三阶段，没点工业
![image](https://user-images.githubusercontent.com/18623783/66122561-9bd8fe80-e612-11e9-8af2-c79e5c240177.png)

相册：
![image](https://user-images.githubusercontent.com/18623783/66122636-d17de780-e612-11e9-935d-1bf3610e07fd.png)

我把分享助力的20%buff去掉之后再次计算结果是75.06，结果与游戏结果基本一致，分享助力的计算加成是不是不应该直接加到家国之光里？

**Comment by ShawnIL** [comment]
。。。。。分享助力根本就不是buff啊。。。仔细阅读一下分享助力的说明。。。这个issue我关了

**Comment by As3ass1n** [comment]
> 。。。。。分享助力根本就不是buff啊。。。仔细阅读一下分享助力的说明。。。这个issue我关了

额。。。我的问题，一直以为是20buff呢，不好意思
